version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: todo
  MYSQL_USER: todo
  MYSQL_PASSWORD: rS&#2Hy@W9

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
      MYSQL_HOST: database
      MYSQL_PORT: 3306

  database:
    image: mysql:8.0.31
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: C2nW=pl(PEm7